//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.GeneralService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneralService.IGeneral")]
    public interface IGeneral {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Login", ReplyAction="http://tempuri.org/IGeneral/LoginResponse")]
        server.BusinessLayer.BusinessUser Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Login", ReplyAction="http://tempuri.org/IGeneral/LoginResponse")]
        System.Threading.Tasks.Task<server.BusinessLayer.BusinessUser> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/SignUp", ReplyAction="http://tempuri.org/IGeneral/SignUpResponse")]
        server.BusinessLayer.BusinessUser SignUp(string email, string password, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/SignUp", ReplyAction="http://tempuri.org/IGeneral/SignUpResponse")]
        System.Threading.Tasks.Task<server.BusinessLayer.BusinessUser> SignUpAsync(string email, string password, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/RemindPassword", ReplyAction="http://tempuri.org/IGeneral/RemindPasswordResponse")]
        server.Result RemindPassword(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/RemindPassword", ReplyAction="http://tempuri.org/IGeneral/RemindPasswordResponse")]
        System.Threading.Tasks.Task<server.Result> RemindPasswordAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/ActualTasks", ReplyAction="http://tempuri.org/IGeneral/ActualTasksResponse")]
        server.BusinessLayer.BussinessMyTask[] ActualTasks(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/ActualTasks", ReplyAction="http://tempuri.org/IGeneral/ActualTasksResponse")]
        System.Threading.Tasks.Task<server.BusinessLayer.BussinessMyTask[]> ActualTasksAsync(int userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralChannel : TaskManager.GeneralService.IGeneral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralClient : System.ServiceModel.ClientBase<TaskManager.GeneralService.IGeneral>, TaskManager.GeneralService.IGeneral {
        
        public GeneralClient() {
        }
        
        public GeneralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public server.BusinessLayer.BusinessUser Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<server.BusinessLayer.BusinessUser> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public server.BusinessLayer.BusinessUser SignUp(string email, string password, string name) {
            return base.Channel.SignUp(email, password, name);
        }
        
        public System.Threading.Tasks.Task<server.BusinessLayer.BusinessUser> SignUpAsync(string email, string password, string name) {
            return base.Channel.SignUpAsync(email, password, name);
        }
        
        public server.Result RemindPassword(string email) {
            return base.Channel.RemindPassword(email);
        }
        
        public System.Threading.Tasks.Task<server.Result> RemindPasswordAsync(string email) {
            return base.Channel.RemindPasswordAsync(email);
        }
        
        public server.BusinessLayer.BussinessMyTask[] ActualTasks(int userID) {
            return base.Channel.ActualTasks(userID);
        }
        
        public System.Threading.Tasks.Task<server.BusinessLayer.BussinessMyTask[]> ActualTasksAsync(int userID) {
            return base.Channel.ActualTasksAsync(userID);
        }
    }
}
